services:
  rfq-api:
    build: .
    working_dir: /app
    env_file:
      - .env.prod
    network_mode: host
    restart: unless-stopped

  rfq-api-testnet:
    build: .
    working_dir: /app
    env_file:
      - .env.testnet
    network_mode: host
    restart: unless-stopped
    command: ["uv", "run", "uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8001"]
